hooks: disable the linter. it doesn't support es6.

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,12 +1,12 @@
 #!/bin/sh
 # (ln -s this file to .git/hooks/pre-commit.)
-echo 'linting...'
-eval 'make lint'
-ret_code=$?
-if [ $ret_code != 0 ]; then
-    echo 'lint errors, aborting commit'
-    exit $ret_code
-fi
+#echo 'linting...'
+#eval 'make lint'
+#ret_code=$?
+#if [ $ret_code != 0 ]; then
+#    echo 'lint errors, aborting commit'
+#    exit $ret_code
+#fi
 eval 'mvn -q clean install'
 ret_code=$?
 if [ $ret_code != 0 ]; then
