Makefile+hooks: add non-invasive linting target+pre-commit check

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,14 +1,12 @@
 #!/bin/sh
 # (ln -s this file to .git/hooks/pre-commit.)
-
-# Codebase isn't stable enough for linting yet.
-#echo 'linting...'
-#eval 'make lint'
-#ret_code=$?
-#if [ $ret_code != 0 ]; then
-#    echo 'lint errors, aborting commit'
-#    exit $ret_code
-#fi
+echo 'linting...'
+eval 'make lint'
+ret_code=$?
+if [ $ret_code != 0 ]; then
+    echo 'lint errors, aborting commit'
+    exit $ret_code
+fi
 echo 'type-checking...'
 eval 'make typecheck'
 ret_code=$?
