test+Makefile+hooks: add test-compiled target.

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -14,10 +14,17 @@ if [ $ret_code != 0 ]; then
     echo 'type errors, aborting commit'
     exit $ret_code
 fi
-echo 'unit tests...'
+echo 'unit tests (uncompiled)...'
 eval 'make test'
 ret_code=$?
 if [ $ret_code != 0 ]; then
     echo 'failure(s) in uncompiled tests, aborting commit'
+    exit $ret_code
+fi
+echo 'unit tests (compiled)...'
+eval 'make test-compiled'
+ret_code=$?
+if [ $ret_code != 0 ]; then
+    echo 'failure(s) in compiled tests, aborting commit'
     exit $ret_code
 fi
